export type Safari = {
  id: string;
  title: string;
  slug: string;
  short_description: string;
  overview: string;
  duration_days: number | null;
  destinations: string[];
  highlights: string[];
  accommodation: string;
  starting_location: string;
  meals: string;
  transport: string;
  included_items: string[];
  excluded_items: string[];
  packing_list: string[];
  important_information: string;
  group_size: string;
  price_from: number | null;
  show_price: boolean;
  currency: string;
  cover_image_url: string;
  status: string;
  featured: boolean;
  display_order: number;
  itinerary_days: { day_number: number; title: string; description: string }[];
};
export type Photo = {
  id: string;
  public_url: string;
  alt_text: string;
  caption: string;
  category: string;
  photographer_name: string;
  status: string;
  published: boolean;
  featured: boolean;
  display_order: number;
  storage_path: string;
};
export type Settings = {
  company_name: string;
  short_description: string;
  whatsapp_number: string;
  phone_number: string;
  email_address: string;
  office_address: string;
  business_hours: string;
  facebook_url: string;
  instagram_url: string;
  youtube_url: string;
  tiktok_url: string;
  seo_title: string;
  seo_description: string;
  [key: string]: string;
};
